function cl_lp = create_class_gpu(Pi,P)
cl_lp=class_lpRadon_matlab.getInstance([Pi.Nt Pi.Nx Pi.Nq Pi.Ntau Pi.Ntheta Pi.Nrho Pi.ni],P.fZgpu,Pi.st,Pi.stadj,...
                                        Pi.idthetatx,Pi.idrhotx,Pi.idthetatauq,Pi.idrhotauq,P.dthetatx,P.drhotx,P.dthetatauq,P.drhotauq,...
                                        P.emul,P.cosmul,P.J,Pi.reorids,Pi.reoridsadj);